spring.application.name=backend

app.domain=http://localhost:8080
email.confirmation.path=/api/auth/confirm


# ===============================
# JWT
# ===============================
jwt.secret=3251cedd55493d911bc45201dc5657916aa96ec43aa498baf24e756ea12239ae
jwt.access-exp-min=15
jwt.refresh-exp-days=14

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/WanderLinkDB
spring.datasource.username=root
spring.datasource.password=rootroot
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ===============================
# Mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pridatchenkovladislav@gmail.com
spring.mail.password=oiiepkugpohcvihi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from.address=noreply@wanderlink.com
app.mail.from.name=Wanderlink